apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: state
  namespace:
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: 127.0.0.1:6379
    - name: redisPassword
      value: "123456"
    - name: actorStateStore
      value: "true"