http:
  address: localhost:8080

service:
  html:
    url: "/page"
  api:
    url: "/api/v1"
    path: "./services"

repos:
  draw-web@gitea:
    url: http://localhost:3000
    repo: draw-web
    branch: main
    user: liuxd
    password: liuxd
  draw-web@local:
    path: "/Users/lxd/Projects/gitea/draw-web"

