package service

import (
	"strconv"
	"testing"

	"github.com/liuxd6825/dapr-go-ddd-sdk/app/domain/sys/currency/command"
	"github.com/liuxd6825/dapr-go-ddd-sdk/app/domain/sys/currency/model"
	"github.com/liuxd6825/dapr-go-ddd-sdk/pkg/utils/idutils"
	xtest2 "github.com/liuxd6825/dapr-go-ddd-sdk/pkg/xtest"
)

func TestCurrencyService_Create(t *testing.T) {
	xtest2.InitEnv_MongoRemoteMaster()
	service := NewCurrencyService()
	ctx := xtest2.NewContext()

	list := getList()
	manyCmd := &command.CurrencyCreateManyCommand{}
	manyCmd.Data = list
	manyCmd.CommandId = idutils.NewId()
	err := service.CreateMany(ctx, manyCmd)
	if err != nil {
		t.Error(err)
	}
}

func TestCurrencyService_DeleteAll(t *testing.T) {
	xtest2.InitEnv_MongoRemoteMaster()
	service := NewCurrencyService()
	ctx := xtest2.NewContext()

	delCmd := &command.CurrencyDeleteCommand{}
	delCmd.CommandId = idutils.NewId()

	err := service.DeleteAll(ctx, delCmd)
	if err != nil {
		t.Error(err)
	}
}

func getList() []*model.Currency {
	cnyRate := 7.1082
	list := []*model.Currency{
		{
			Area:  "中国",
			Name:  "人民币",
			Code1: "CNY",
			Code2: "RMB",
			Code3: "",
			Rate:  7.1082,
		},
		{
			Area:  "美国",
			Name:  "美元",
			Code1: "USD",
			Code2: "",
			Code3: "",
			Rate:  1.0,
		},
		{
			Area:  "欧元区",
			Name:  "欧元",
			Code1: "EUR",
			Code2: "",
			Code3: "",
			Rate:  0.86358,
		},
		{
			Area:  "日本",
			Name:  "日元",
			Code1: "JPY",
			Code2: "",
			Code3: "",
			Rate:  155.53,
		},
		{
			Area:  "英国",
			Name:  "英镑",
			Code1: "GBP",
			Code2: "",
			Code3: "",
			Rate:  0.76067,
		},
		{
			Area:  "澳大利亚",
			Name:  "澳大利亚元",
			Code1: "AUD",
			Code2: "",
			Code3: "",
			Rate:  1.5363,
		},
		{
			Area:  "加拿大",
			Name:  "加拿大元",
			Code1: "CAD",
			Code2: "",
			Code3: "",
			Rate:  1.3983,
		},
		{
			Area:  "瑞士",
			Name:  "瑞士法郎",
			Code1: "CHF",
			Code2: "",
			Code3: "",
			Rate:  0.9213,
		},
		{
			Area:  "香港",
			Name:  "港元",
			Code1: "HKD",
			Code2: "",
			Code3: "",
			Rate:  7.786,
		},
		{
			Area:  "新加坡",
			Name:  "新加坡元",
			Code1: "SGD",
			Code2: "",
			Code3: "",
			Rate:  1.3020,
		},
		{
			Area:  "韩国",
			Name:  "韩元",
			Code1: "KRW",
			Code2: "",
			Code3: "",
			Rate:  1459.49,
		},
		{
			Area:  "新西兰",
			Name:  "新西兰元",
			Code1: "NZD",
			Code2: "",
			Code3: "",
			Rate:  1.7668,
		},
		{
			Area:  "瑞典",
			Name:  "瑞典克朗",
			Code1: "SEK",
			Code2: "",
			Code3: "",
			Rate:  9.4825,
		},
		{
			Area:  "挪威",
			Name:  "挪威克朗",
			Code1: "NOK",
			Code2: "",
			Code3: "",
			Rate:  9.4324,
		},
		{
			Area:  "墨西哥",
			Name:  "墨西哥比索",
			Code1: "MXN",
			Code2: "",
			Code3: "",
			Rate:  17.2045,
		},
		{
			Area:  "印度",
			Name:  "印度卢比",
			Code1: "INR",
			Code2: "",
			Code3: "",
			Rate:  88.629,
		},
		{
			Area:  "俄罗斯",
			Name:  "俄罗斯卢布",
			Code1: "RUB",
			Code2: "",
			Code3: "",
			Rate:  82.0446,
		},
		{
			Area:  "南非",
			Name:  "南非兰特",
			Code1: "ZAR",
			Code2: "",
			Code3: "",
			Rate:  17.1848,
		},
		{
			Area:  "巴西",
			Name:  "巴西雷亚尔",
			Code1: "BRL",
			Code2: "",
			Code3: "",
			Rate:  5.091,
		},
		{
			Area:  "土耳其",
			Name:  "土耳其里拉",
			Code1: "TRY",
			Code2: "",
			Code3: "",
			Rate:  42.3418,
		},
		{
			Area:  "台湾",
			Name:  "新台币",
			Code1: "TWD",
			Code2: "",
			Code3: "",
			Rate:  31.136,
		},
		{
			Area:  "泰国",
			Name:  "泰铢",
			Code1: "THB",
			Code2: "",
			Code3: "",
			Rate:  32.401,
		},
		{
			Area:  "马来西亚",
			Name:  "马来西亚林吉特",
			Code1: "MYR",
			Code2: "",
			Code3: "",
			Rate:  4.1663,
		},
		{
			Area:  "印度尼西亚",
			Name:  "印度尼西亚盾",
			Code1: "IDR",
			Code2: "",
			Code3: "",
			Rate:  16736.1,
		},
		{
			Area:  "菲律宾",
			Name:  "菲律宾比索",
			Code1: "PHP",
			Code2: "",
			Code3: "",
			Rate:  58.922,
		},
		{
			Area:  "越南",
			Name:  "越南盾",
			Code1: "VND",
			Code2: "",
			Code3: "",
			Rate:  25450.0,
		},
		{
			Area:  "阿联酋",
			Name:  "阿联酋迪拉姆",
			Code1: "AED",
			Code2: "",
			Code3: "",
			Rate:  3.6725,
		},
		{
			Area:  "沙特阿拉伯",
			Name:  "沙特里亚尔",
			Code1: "SAR",
			Code2: "",
			Code3: "",
			Rate:  3.75,
		},
		{
			Area:  "以色列",
			Name:  "以色列新谢克尔",
			Code1: "ILS",
			Code2: "",
			Code3: "",
			Rate:  3.2772,
		},
		{
			Area:  "埃及",
			Name:  "埃及镑",
			Code1: "EGP",
			Code2: "",
			Code3: "",
			Rate:  47.95,
		},
		{
			Area:  "尼日利亚",
			Name:  "尼日利亚奈拉",
			Code1: "NGN",
			Code2: "",
			Code3: "",
			Rate:  1475.0,
		},
		{
			Area:  "肯尼亚",
			Name:  "肯尼亚先令",
			Code1: "KES",
			Code2: "",
			Code3: "",
			Rate:  131.0,
		},
		{
			Area:  "加纳",
			Name:  "加纳塞地",
			Code1: "GHS",
			Code2: "",
			Code3: "",
			Rate:  14.9,
		},
		{
			Area:  "巴基斯坦",
			Name:  "巴基斯坦卢比",
			Code1: "PKR",
			Code2: "",
			Code3: "",
			Rate:  278.0,
		},
		{
			Area:  "孟加拉国",
			Name:  "孟加拉塔卡",
			Code1: "BDT",
			Code2: "",
			Code3: "",
			Rate:  117.0,
		},
		{
			Area:  "斯里兰卡",
			Name:  "斯里兰卡卢比",
			Code1: "LKR",
			Code2: "",
			Code3: "",
			Rate:  305.0,
		},
		{
			Area:  "阿根廷",
			Name:  "阿根廷比索",
			Code1: "ARS",
			Code2: "",
			Code3: "",
			Rate:  915.0,
		},
		{
			Area:  "智利",
			Name:  "智利比索",
			Code1: "CLP",
			Code2: "",
			Code3: "",
			Rate:  935.0,
		},
		{
			Area:  "哥伦比亚",
			Name:  "哥伦比亚比索",
			Code1: "COP",
			Code2: "",
			Code3: "",
			Rate:  4050.0,
		},
		{
			Area:  "秘鲁",
			Name:  "秘鲁索尔",
			Code1: "PEN",
			Code2: "",
			Code3: "",
			Rate:  3.75,
		},
		{
			Area:  "委内瑞拉",
			Name:  "委内瑞拉玻利瓦尔",
			Code1: "VES",
			Code2: "",
			Code3: "",
			Rate:  3630000.0,
		},
		{
			Area:  "丹麦",
			Name:  "丹麦克朗",
			Code1: "DKK",
			Code2: "",
			Code3: "",
			Rate:  6.963,
		},
		{
			Area:  "波兰",
			Name:  "波兰兹罗提",
			Code1: "PLN",
			Code2: "",
			Code3: "",
			Rate:  4.025,
		},
		{
			Area:  "匈牙利",
			Name:  "匈牙利福林",
			Code1: "HUF",
			Code2: "",
			Code3: "",
			Rate:  331.7,
		},
		{
			Area:  "捷克",
			Name:  "捷克克朗",
			Code1: "CZK",
			Code2: "",
			Code3: "",
			Rate:  23.45,
		},
		{
			Area:  "冰岛",
			Name:  "冰岛克朗",
			Code1: "ISK",
			Code2: "",
			Code3: "",
			Rate:  139.5,
		},
		{
			Area:  "克罗地亚",
			Name:  "克罗地亚库纳",
			Code1: "HRK",
			Code2: "",
			Code3: "",
			Rate:  7.0,
		},
		{
			Area:  "罗马尼亚",
			Name:  "罗马尼亚列伊",
			Code1: "RON",
			Code2: "",
			Code3: "",
			Rate:  4.65,
		},
		{
			Area:  "保加利亚",
			Name:  "保加利亚列弗",
			Code1: "BGN",
			Code2: "",
			Code3: "",
			Rate:  1.84,
		},
		{
			Area:  "塞尔维亚",
			Name:  "塞尔维亚第纳尔",
			Code1: "RSD",
			Code2: "",
			Code3: "",
			Rate:  109.0,
		},
		{
			Area:  "阿尔巴尼亚",
			Name:  "阿尔巴尼亚列克",
			Code1: "ALL",
			Code2: "",
			Code3: "",
			Rate:  93.5,
		},
		{
			Area:  "乌克兰",
			Name:  "乌克兰格里夫纳",
			Code1: "UAH",
			Code2: "",
			Code3: "",
			Rate:  42.3243,
		},
		{
			Area:  "白俄罗斯",
			Name:  "白俄罗斯卢布",
			Code1: "BYN",
			Code2: "",
			Code3: "",
			Rate:  3.28,
		},
		{
			Area:  "哈萨克斯坦",
			Name:  "哈萨克斯坦坚戈",
			Code1: "KZT",
			Code2: "",
			Code3: "",
			Rate:  450.0,
		},
		{
			Area:  "乌兹别克斯坦",
			Name:  "乌兹别克斯坦索姆",
			Code1: "UZS",
			Code2: "",
			Code3: "",
			Rate:  12700.0,
		},
		{
			Area:  "格鲁吉亚",
			Name:  "格鲁吉亚拉里",
			Code1: "GEL",
			Code2: "",
			Code3: "",
			Rate:  2.7,
		},
		{
			Area:  "阿塞拜疆",
			Name:  "阿塞拜疆马纳特",
			Code1: "AZN",
			Code2: "",
			Code3: "",
			Rate:  1.7,
		},
		{
			Area:  "亚美尼亚",
			Name:  "亚美尼亚德拉姆",
			Code1: "AMD",
			Code2: "",
			Code3: "",
			Rate:  387.0,
		},
		{
			Area:  "摩尔多瓦",
			Name:  "摩尔多瓦列伊",
			Code1: "MDL",
			Code2: "",
			Code3: "",
			Rate:  17.8,
		},
		{
			Area:  "澳门",
			Name:  "澳门元",
			Code1: "MOP",
			Code2: "",
			Code3: "",
			Rate:  8.02,
		},
		{
			Area:  "柬埔寨",
			Name:  "柬埔寨瑞尔",
			Code1: "KHR",
			Code2: "",
			Code3: "",
			Rate:  4100.0,
		},
		{
			Area:  "老挝",
			Name:  "老挝基普",
			Code1: "LAK",
			Code2: "",
			Code3: "",
			Rate:  21800.0,
		},
		{
			Area:  "缅甸",
			Name:  "缅甸元",
			Code1: "MMK",
			Code2: "",
			Code3: "",
			Rate:  2100.0,
		},
		{
			Area:  "文莱",
			Name:  "文莱元",
			Code1: "BND",
			Code2: "",
			Code3: "",
			Rate:  1.35,
		},
		{
			Area:  "蒙古",
			Name:  "蒙古图格里克",
			Code1: "MNT",
			Code2: "",
			Code3: "",
			Rate:  3450.0,
		},
		{
			Area:  "尼泊尔",
			Name:  "尼泊尔卢比",
			Code1: "NPR",
			Code2: "",
			Code3: "",
			Rate:  133.0,
		},
		{
			Area:  "不丹",
			Name:  "不丹努尔特鲁姆",
			Code1: "BTN",
			Code2: "",
			Code3: "",
			Rate:  83.0,
		},
		{
			Area:  "马尔代夫",
			Name:  "马尔代夫拉菲亚",
			Code1: "MVR",
			Code2: "",
			Code3: "",
			Rate:  15.4,
		},
		{
			Area:  "阿富汗",
			Name:  "阿富汗尼",
			Code1: "AFN",
			Code2: "",
			Code3: "",
			Rate:  70.0,
		},
		{
			Area:  "伊朗",
			Name:  "伊朗里亚尔",
			Code1: "IRR",
			Code2: "",
			Code3: "",
			Rate:  42000.0,
		},
		{
			Area:  "伊拉克",
			Name:  "伊拉克第纳尔",
			Code1: "IQD",
			Code2: "",
			Code3: "",
			Rate:  1310.0,
		},
		{
			Area:  "叙利亚",
			Name:  "叙利亚镑",
			Code1: "SYP",
			Code2: "",
			Code3: "",
			Rate:  13000.0,
		},
		{
			Area:  "黎巴嫩",
			Name:  "黎巴嫩镑",
			Code1: "LBP",
			Code2: "",
			Code3: "",
			Rate:  89500.0,
		},
		{
			Area:  "约旦",
			Name:  "约旦第纳尔",
			Code1: "JOD",
			Code2: "",
			Code3: "",
			Rate:  0.709,
		},
		{
			Area:  "卡塔尔",
			Name:  "卡塔尔里亚尔",
			Code1: "QAR",
			Code2: "",
			Code3: "",
			Rate:  3.64,
		},
		{
			Area:  "科威特",
			Name:  "科威特第纳尔",
			Code1: "KWD",
			Code2: "",
			Code3: "",
			Rate:  0.307,
		},
		{
			Area:  "巴林",
			Name:  "巴林第纳尔",
			Code1: "BHD",
			Code2: "",
			Code3: "",
			Rate:  0.376,
		},
		{
			Area:  "阿曼",
			Name:  "阿曼里亚尔",
			Code1: "OMR",
			Code2: "",
			Code3: "",
			Rate:  0.385,
		},
		{
			Area:  "也门",
			Name:  "也门里亚尔",
			Code1: "YER",
			Code2: "",
			Code3: "",
			Rate:  250.0,
		},
		{
			Area:  "摩洛哥",
			Name:  "摩洛哥迪拉姆",
			Code1: "MAD",
			Code2: "",
			Code3: "",
			Rate:  9.261,
		},
		{
			Area:  "阿尔及利亚",
			Name:  "阿尔及利亚第纳尔",
			Code1: "DZD",
			Code2: "",
			Code3: "",
			Rate:  134.0,
		},
		{
			Area:  "突尼斯",
			Name:  "突尼斯第纳尔",
			Code1: "TND",
			Code2: "",
			Code3: "",
			Rate:  3.1,
		},
		{
			Area:  "利比亚",
			Name:  "利比亚第纳尔",
			Code1: "LYD",
			Code2: "",
			Code3: "",
			Rate:  4.85,
		},
		{
			Area:  "苏丹",
			Name:  "苏丹镑",
			Code1: "SDG",
			Code2: "",
			Code3: "",
			Rate:  600.0,
		},
		{
			Area:  "埃塞俄比亚",
			Name:  "埃塞俄比亚比尔",
			Code1: "ETB",
			Code2: "",
			Code3: "",
			Rate:  57.0,
		},
		{
			Area:  "索马里",
			Name:  "索马里先令",
			Code1: "SOS",
			Code2: "",
			Code3: "",
			Rate:  570.0,
		},
		{
			Area:  "坦桑尼亚",
			Name:  "坦桑尼亚先令",
			Code1: "TZS",
			Code2: "",
			Code3: "",
			Rate:  2600.0,
		},
		{
			Area:  "乌干达",
			Name:  "乌干达先令",
			Code1: "UGX",
			Code2: "",
			Code3: "",
			Rate:  3750.0,
		},
		{
			Area:  "卢旺达",
			Name:  "卢旺达法郎",
			Code1: "RWF",
			Code2: "",
			Code3: "",
			Rate:  1300.0,
		},
		{
			Area:  "布隆迪",
			Name:  "布隆迪法郎",
			Code1: "BIF",
			Code2: "",
			Code3: "",
			Rate:  2850.0,
		},
		{
			Area:  "刚果（金）",
			Name:  "刚果法郎",
			Code1: "CDF",
			Code2: "",
			Code3: "",
			Rate:  2800.0,
		},
		{
			Area:  "赞比亚",
			Name:  "赞比亚克瓦查",
			Code1: "ZMW",
			Code2: "",
			Code3: "",
			Rate:  26.0,
		},
		{
			Area:  "津巴布韦",
			Name:  "津巴布韦元",
			Code1: "ZWL",
			Code2: "",
			Code3: "",
			Rate:  13.0,
		},
		{
			Area:  "博茨瓦纳",
			Name:  "博茨瓦纳普拉",
			Code1: "BWP",
			Code2: "",
			Code3: "",
			Rate:  14.0,
		},
		{
			Area:  "纳米比亚",
			Name:  "纳米比亚元",
			Code1: "NAD",
			Code2: "",
			Code3: "",
			Rate:  18.0,
		},
		{
			Area:  "莱索托",
			Name:  "莱索托洛蒂",
			Code1: "LSL",
			Code2: "",
			Code3: "",
			Rate:  18.0,
		},
		{
			Area:  "斯威士兰",
			Name:  "斯威士兰里朗吉尼",
			Code1: "SZL",
			Code2: "",
			Code3: "",
			Rate:  18.0,
		},
		{
			Area:  "毛里求斯",
			Name:  "毛里求斯卢比",
			Code1: "MUR",
			Code2: "",
			Code3: "",
			Rate:  46.0,
		},
		{
			Area:  "塞舌尔",
			Name:  "塞舌尔卢比",
			Code1: "SCR",
			Code2: "",
			Code3: "",
			Rate:  14.0,
		},
		{
			Area:  "马达加斯加",
			Name:  "马达加斯加阿里亚里",
			Code1: "MGA",
			Code2: "",
			Code3: "",
			Rate:  4500.0,
		},
		{
			Area:  "科摩罗",
			Name:  "科摩罗法郎",
			Code1: "KMF",
			Code2: "",
			Code3: "",
			Rate:  491.9,
		},
	}
	for i, c := range list {
		c.Id = idutils.NewId()
		c.Order = i
		cnRate := c.Rate / cnyRate
		valStr := strconv.FormatFloat(cnRate, 'f', 4, 64)
		if val, err := strconv.ParseFloat(valStr, 64); err == nil {
			c.CnRate = val
		}
	}
	return list
}
