apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: applogger
  namespace:
spec:
  type: applogger.mongodb
  version: v1
  metadata:
    - name: host
      value: 192.168.120.96:27018, 192.168.120.96:27019, 192.168.120.96:27020
    - name: replica-set
      value: mongors
    - name: databaseName
      value: "test_duxm_service_applog"
    - name: username
      value: "dapr"
    - name: password
      value: "123456"
