package packages

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

// SinglePackageData 存储单个包的解析结果
type SinglePackageData struct {
	Alias      string   // 生成代码中使用的别名 (例如 pkg0)
	ImportPath string   // 完整的导入路径
	PkgName    string   // 原始包名 (例如 utils)
	Types      []string // 导出的类型
	Functions  []string // 导出的函数
	Constants  []string // 导出的常量
	Variables  []string // 导出的变量
}

// GlobalData 用于渲染整个文件
type GlobalData struct {
	OutPackageName string              // 输出文件的包名
	Packages       []SinglePackageData // 所有扫描到的包
}

// 模板：支持多包导入和别名
const codeTemplate = `// Code generated by scriggo-gen; DO NOT EDIT.
package {{.OutPackageName}}

import (
	"github.com/open2b/scriggo/native"
	{{- range .Packages}}
	{{.Alias}} "{{.ImportPath}}"
	{{- end}}
)

// Packages 返回所有扫描到的包的 Scriggo 声明
func Packages() native.Packages {
	pkgs := native.Packages{}

	{{- range $pkg := .Packages}}
	// Package: {{$pkg.ImportPath}}
	pkgs["{{$pkg.ImportPath}}"] = native.Package{
		Name: "{{$pkg.PkgName}}",
		Declarations: native.Declarations{
			// Functions
			{{- range $pkg.Functions}}
			"{{.}}": {{$pkg.Alias}}.{{.}},
			{{- end}}

			// Types
			{{- range $pkg.Types}}
			"{{.}}": (*{{$pkg.Alias}}.{{.}})(nil),
			{{- end}}
			
			// Constants
			{{- range $pkg.Constants}}
			"{{.}}": {{$pkg.Alias}}.{{.}},
			{{- end}}

			// Variables
			{{- range $pkg.Variables}}
			"{{.}}": &{{$pkg.Alias}}.{{.}},
			{{- end}}
		},
	}
	{{- end}}

	return pkgs
}
`

/*
	srcDir := flag.String("src", "", "根源目录路径 (必须)")
	baseImportPath := flag.String("path", "", "根目录对应的基础导入路径 (必须)")
	outputFile := flag.String("out", "scriggo_exports.go", "输出文件名")
	outPkgName := flag.String("pkg", "exports", "生成文件的包名")
	recursive := flag.Bool("recursive", false, "是否递归扫描子目录")
*/

type MakeOption struct {
	SrcDir     string   // 源目录路径
	ImportPath string   // 根目录对应的基础导入路径
	OutPkgName string   // 输出的包名称
	OutputFile string   // 输出的文件
	Recursive  bool     // 是否包含子目录
	Cancels    []string // 取消的目录或文件部分
}

func (opt *MakeOption) Valid() error {
	if opt.SrcDir == "" {
		return fmt.Errorf("SrcDir is empty")
	}
	if opt.ImportPath == "" {
		return fmt.Errorf("ImportPath is empty")
	}
	if opt.OutPkgName == "" {
		return fmt.Errorf("OutPkgName is empty")
	}
	if opt.OutputFile == "" {
		return fmt.Errorf("OutputFile is empty")
	}
	return nil
}

func Make(opts MakeOption) error {
	if err := opts.Valid(); err != nil {
		return err
	}

	srcDir := opts.SrcDir
	baseImportPath := opts.ImportPath
	outPkgName := opts.OutPkgName
	outputFile := opts.OutputFile
	recursive := opts.Recursive
	cancelList := opts.Cancels
	cancelList = append(cancelList, "/internal/")

	absSrcDir, _ := filepath.Abs(srcDir)
	absOutFile, _ := filepath.Abs(outputFile)

	var scannedPackages []SinglePackageData
	packageCounter := 0

	// 2. 扫描所有目录
	dirsToParse := make(map[string]string) // map[AbsPath]RelativePath

	filepath.WalkDir(absSrcDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}

		// --- 过滤逻辑开始 ---

		// 检查当前节点（文件或目录名）是否包含屏蔽词
		if isCancelled(path, cancelList) {
			if d.IsDir() {
				// 如果是目录且包含屏蔽词（例如 internal），跳过整个目录
				return filepath.SkipDir
			}
			// 如果是文件，直接跳过
			return nil
		}

		// --- 过滤逻辑结束 ---

		if d.IsDir() {
			// 非递归模式处理
			if !recursive && path != absSrcDir {
				return filepath.SkipDir
			}
			// 排除隐藏目录和 vendor
			if strings.HasPrefix(d.Name(), ".") || d.Name() == "vendor" {
				return filepath.SkipDir
			}

			// 检查目录下是否有有效的 Go 文件
			hasGo := false
			entries, _ := os.ReadDir(path)
			for _, e := range entries {
				if e.IsDir() {
					continue
				}
				// 再次检查文件名是否被屏蔽
				if isCancelled(e.Name(), cancelList) {
					continue
				}

				if strings.HasSuffix(e.Name(), ".go") && !strings.HasSuffix(e.Name(), "_test.go") {
					fullPath := filepath.Join(path, e.Name())
					if fullPath != absOutFile {
						hasGo = true
						break
					}
				}
			}

			if hasGo {
				rel, _ := filepath.Rel(absSrcDir, path)
				dirsToParse[path] = rel
			}
		}
		return nil
	})

	fset := token.NewFileSet()

	// 3. 排序目录 (保证生成稳定性)
	var sortedDirs []string
	for k := range dirsToParse {
		sortedDirs = append(sortedDirs, k)
	}
	sort.Strings(sortedDirs)

	for _, dirPath := range sortedDirs {
		relPath := dirsToParse[dirPath]

		// 4. 解析目录
		pkgs, err := parser.ParseDir(fset, dirPath, func(fi os.FileInfo) bool {
			// A. 排除输出文件自身
			fullPath := filepath.Join(dirPath, fi.Name())
			if fullPath == absOutFile {
				return false
			}
			// B. 排除测试文件
			if strings.HasSuffix(fi.Name(), "_test.go") {
				return false
			}
			// C. 排除包含屏蔽词的文件
			if isCancelled(dirPath+"/"+fi.Name(), cancelList) {
				return false
			}
			return true
		}, 0)

		if err != nil {
			log.Printf("解析目录 %s 出错: %v", dirPath, err)
			continue
		}

		for pkgName, pkgAst := range pkgs {
			if pkgName == "main" {
				continue
			}

			fullImportPath := baseImportPath
			if relPath != "." && relPath != "" {
				slashRel := filepath.ToSlash(relPath)
				fullImportPath = fmt.Sprintf("%s/%s", strings.TrimRight(baseImportPath, "/"), slashRel)
			}

			data := SinglePackageData{
				Alias:      fmt.Sprintf("pkg%d", packageCounter),
				ImportPath: fullImportPath,
				PkgName:    pkgName,
			}
			packageCounter++

			hasContent := false

			ast.Inspect(pkgAst, func(n ast.Node) bool {
				switch x := n.(type) {
				case *ast.FuncDecl:
					v := n.(*ast.FuncDecl)
					// 1. 必须导出 (大写)
					if !x.Name.IsExported() {
						return false
					}
					// 2. 必须是普通函数 (非方法)
					if x.Recv != nil {
						return false
					}
					// 3. 【新增】必须非泛型 (Scriggo 不支持直接导入未实例化的泛型)
					if v.Type.TypeParams != nil && len(v.Type.TypeParams.List) > 0 {
						// log.Printf("跳过泛型函数: %s.%s", pkgName, x.Name.Name)
						return false
					}

					data.Functions = append(data.Functions, x.Name.Name)
					hasContent = true
				case *ast.GenDecl:
					if x.Tok != token.TYPE && x.Tok != token.CONST && x.Tok != token.VAR {
						return true
					}
					for _, spec := range x.Specs {
						switch s := spec.(type) {
						case *ast.TypeSpec:
							if s.Name.IsExported() {
								// 4. 【新增】跳过泛型类型
								if s.TypeParams != nil && len(s.TypeParams.List) > 0 {
									// log.Printf("跳过泛型类型: %s.%s", pkgName, s.Name.Name)
									continue
								}
								data.Types = append(data.Types, s.Name.Name)
								hasContent = true
							}
						case *ast.ValueSpec:
							for _, name := range s.Names {
								if name.IsExported() {
									if x.Tok == token.CONST {
										data.Constants = append(data.Constants, name.Name)
										hasContent = true
									} else if x.Tok == token.VAR {
										data.Variables = append(data.Variables, name.Name)
										hasContent = true
									}
								}
							}
						}
					}
				}
				return true
			})

			if hasContent {
				scannedPackages = append(scannedPackages, data)
			}
		}
	}

	globalData := GlobalData{
		OutPackageName: outPkgName,
		Packages:       scannedPackages,
	}

	if err := generateFile(globalData, outputFile); err != nil {
		log.Fatalf("生成失败: %v", err)
		return err
	}
	return nil
}

// isCancelled 检查名称是否包含任一屏蔽词
func isCancelled(name string, cancels []string) bool {
	if len(cancels) == 0 {
		return false
	}
	for _, c := range cancels {
		// 这里使用 Contains，只要名称中包含该字符串即屏蔽
		if strings.Contains(name, c) {
			return true
		}
	}
	return false
}

func generateFile(data GlobalData, filepathStr string) error {
	tmpl, err := template.New("scriggo").Parse(codeTemplate)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Println("格式化失败，写入原始内容以供调试...")
		os.WriteFile(filepathStr, buf.Bytes(), 0644)
		return err
	}

	dir := filepath.Dir(filepathStr)
	if dir != "." {
		os.MkdirAll(dir, 0755)
	}

	fmt.Printf("成功生成文件: %s, 包含 %d 个包\n", filepathStr, len(data.Packages))
	return os.WriteFile(filepathStr, formatted, 0644)
}
