apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: applogger
  namespace:
spec:
  type: applogger.mongodb
  version: v1
  metadata:
    - name: host
      value: 122.143.11.104:27018, 122.143.11.104:27019, 122.143.11.104:27020
    - name: replica-set
      value: mongors
    - name: databaseName
      value: "duxm_fund_master_service_dapr_applog"
    - name: username
      value: "dapr"
    - name: password
      value: "123456"
