http:
  address: localhost:8080

service:
  html:
    url: "/page"
  api:
    url: "/api/v1"
    path: "./services"

repos:
  gitea:
    draw-web:
      url: http://localhost:3000
      repo: draw-web
      branch: main
      user: liuxd
      password: liuxd
  file:
    draw-web:
      path: "/Users/lxd/Projects/gitea/draw-web"

