@startuml
actor 用户 as user
boundary HomeUI as homeui
control HomeUC as homeuc
boundary 卡片选择UI as selectui
control 卡片选择UC as selectuc
boundary 自定义卡片UI as customui
control 自定义卡片UC as customuc
entity Home as home
entity Group as group
entity Card as card
entity 卡片定义 as cardFile


user -> homeui : 点击编辑首页
activate homeui

homeui -> homeuc : 切换编辑模式
deactivate homeui

user -> homeui : 点击添加卡片
activate homeui
homeui -> homeuc : 打开选择卡片菜单【系统卡片、自定义卡片】
deactivate

user -> selectui : [选择系统卡片]打开系统卡片选择页面
activate selectui
selectui -> selectuc : 加载系统卡片数据
activate selectuc
selectuc -> cardFile : 加载系统卡片定义数据【卡片定义数据】
deactivate selectui
deactivate selectuc

user -> selectui : 勾选卡片进行添加
activate selectui
selectui -> selectuc : 添加卡片【数据暂存】
deactivate selectui

user -> customui : [选择自定义卡片]打开自定义卡片添加页面
user -> customui : 用户填写自定义卡片信息【标题、副标题、链接地址、打开方式、图标】
activate customui
customui -> customuc : 添加卡片【数据暂存】
deactivate customui

user -> homeui : 点击结束编辑
activate homeui
homeui -> homeuc : 保存首页编辑后的所有数据【新增、更新、删除】
activate homeuc
homeuc -> home : 检查用户首页数据是否存在
activate home
home -> home : [用户首页不存在]新增用户首页
home -> group : 保存组信息【新增、更新、删除】
home -> card : 保存卡片信息【新增、更新、删除】

@enduml