@startuml
left to right direction

actor "用户" as  user
actor "管理员" as admin
actor "开发者" as dev

usecase "打开启始页" as openPageUC
usecase "编辑启始页" as editPageUC
usecase "查询应用卡片" as findAppCard

user -- openPageUC
user -- editPageUC
editPageUC -- findAppCard
admin -- (保存为\n系统默认)

dev -- (注册卡片)
dev -- (编辑卡片)
dev -- (删除卡片)
admin -- user


note right of openPageUC: 用户需要输入用户名和密码才能登录?
@enduml