@startuml
left to right direction

class 银行流水 {

}
class 审计标记类型 {
    金额可疑
    频率可疑
    对手方可疑
    时间可疑
}
class 审计标记 {
}
class 审计对象 {
}
class 阀值 {
    一进一出天数 int
    单笔大金额 int
}
时间可疑 <|-- 审计标记
审计对象 "*" -- "1" 阀值
审计对象 -- "*" 审计标记
审计标记 -- "1" 银行流水
审计标记 -- 审计标记类型
@enduml